### Cek Ongkir JNE
POST https://rajaongkir.komerce.id/api/v1/calculate/domestic-cost
Content-Type: application/x-www-form-urlencoded
Accept: application/json
key: CbBfAF2V89e838b422386bbezPPs7X3B

origin=64999&destination=64942&weight=1000&courier=jne